version: '2'

services:

  omeka-s:
    build: ./
    ports:
      - "9018:80"
    volumes:
      - ./modules/:/var/www/html/tdc/modules/
      - ./themes/:/var/www/html/tdc/themes/
      - ./files/:/var/www/html/tdc/files/
      - ./config/:/var/www/html/tdc/config/
      - ./htaccess:/var/www/html/tdc/.htaccess
      - ./imagemagick-policy.xml:/var/www/html/tdc/imagemagick-policy.xml
    restart: "no"
