version: '2'

services:

  omeka-s:
    build: ./
    ports:
      - "9019:80"
    volumes:
      - ./modules/:/var/www/html/maredsous/modules/
      - ./themes/:/var/www/html/maredsous/themes/
      - ./files/:/var/www/html/maredsous/files/
      - ./config/:/var/www/html/maredsous/config/
      - ./htaccess:/var/www/html/maredsous/.htaccess
      - ./imagemagick-policy.xml:/var/www/html/maredsous/imagemagick-policy.xml
    restart: "no"
