<!-- <div class="item-showcase">
<?php foreach ($attachments as $attachment): ?>
    <div class="item resource">
    <?php
    $item = $attachment->item();
    if ($item):
    ?>
        <?php
        $media = $attachment->media() ?: $item->primaryMedia();
        if ($media):
            echo $item->linkRaw($this->thumbnail($media, $this->thumbnailType));
        endif;
        ?>
        <?php $showTitleOption = $this->showTitleOption; ?>
        <?php if ($showTitleOption == 'item_title'): ?>
        <h3><?php echo $item->link($item->displayTitle()); ?></h3>
        <?php elseif ($showTitleOption == 'file_name'): ?>
        <h3><?php echo $media->displayTitle(); ?></h3>
        <?php endif; ?>
    <?php endif; ?>

    <?php
    $caption = $attachment->caption();
    if ($caption):
    ?>
        <div class="caption"><?php echo $caption; ?></div>
    <?php endif; ?>
    </div>
<?php endforeach; ?>
</div> -->

<style>
.heading::after{
    content: " — ";
    color:ad3e3f;
    font-family: 'Montserrat', sans-serif;
    font-size: xx-large;
}
.heading-white::after{
    content: " — ";
    color:white;
    font-family: 'Montserrat', sans-serif;
    font-size: xx-large;
}
</style>
<?php
$media = $attachment->media();
$oUrl = $media->originalUrl(); 
$originalUrl = str_replace('http://', 'https://', $oUrl);

?>
<?php if(!$embed):?>
<section class="section" style="background-color: <?php echo $colour; ?>;">
    <?php if($heading):?>
    <div class="text-center heading<?php if($colour == 'ad3e3f'): ?>-white<?php endif;?>">
        <h5 class="title" <?php if($colour == 'ad3e3f'): ?>style="color: white;"<?php endif;?>><?php echo $heading; ?></h5>
    </div>
    <?php endif;?>    
    <div class="justify-content-center d-flex">
        <iframe src="<?php echo $originalUrl; ?>" style="width: 800px; height: 600px;" allowfullscreen="true">
        </iframe>
    </div>
</section>
<?php endif;?>

<?php if($embed):?>
<section class="section" style="background-color: <?php echo $colour; ?>;">
    <?php if($heading):?>
    <div class="text-center heading<?php if($colour == 'ad3e3f'): ?>-white<?php endif;?>">
        <h5 class="title" <?php if($colour == 'ad3e3f'): ?>style="color: white;"<?php endif;?>><?php echo $heading; ?></h5>
    </div>
    <?php endif;?>    
    <div class="justify-content-center d-flex">
        <a href="<?php echo $originalUrl; ?>" target="_blank">PDF
        </a>
    </div>
</section>
<?php endif;?>