<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
//$this->htmlElement('html')->setAttribute('class', "has-navbar-fixed-top");

$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet($this->assetUrl('css/style.min.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/selectize.css'));
//$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700italic,700');
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/slick.js'));
$this->headScript()->prependFile($this->assetUrl('js/clamp.min.js'));
$this->headScript()->prependFile($this->assetUrl('js/selectize.js'));
$this->headScript()->prependFile($this->assetUrl('js/readmore.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));

$this->trigger('view.layout');
$userBar = $this->userBar();
$url = $this->serverUrl(true);
if (strpos($url, 'page/home') !== false) {
    $home = true;
}else{
  $home = false;
}
if (strpos($url, 'page/digitale_editie_') !== false) {
  $vol = true;
}else{
$vol = false;
}
$lan = preg_replace('/.*maredsous-(en|nl|fr)\/page.*/','${1}',$url);
$navs = [];
switch ($lan){
  case "nl":
    $taal = "Nederlands";
    $titleSite = 'HET BREVIER VAN<br> GERAARDSBERGEN';
    $navs = ['Credits', 'Partners', 'Home', 'Stories', 'Digitale editie', 'Brevier van Geraardsbergen', '15de eeuws Meesterwerk', 'Onderzoek en Conservatie'];
    $tekstBanner = 'Het Brevier van de heilige Adrianus van Geraardsbergen, vandaag
    bewaard in de Abdij van Maredsous, dateert van 1450, toen het
    graafschap Vlaanderen in handen was van Filips de Goede, hertog
    van Bourgondië. Het Brevier is een sleutelwerk voor de kennis van de Vlaamse miniatuurschilderkunst van het midden van de vijftiende eeuw.';
    $bannerTitle = 'Een Bourgondisch handschrift';
    $bannerSubtitle = 'bewaard in de Abdij van Maredsous';
    $footerViewerTekst = 'Bekijk het volume in onze online viewer';
    $readMore = 'Lees meer';
    break;
  case "fr":
    $taal = "Français";
    $titleSite = 'LE BRÉVIAIRE<br> DE GRAMMONT';
    $navs = ['Colophon', 'Partenaires', 'Home', 'Histoires', 'Édition numérique', 'Le bréviaire de Saint-Adrien de Grammont', 'Un chef d’œuvre du XVe siècle', 'Recherche & conservation'];
    $tekstBanner = 'Le Bréviaire de Saint-Adrien de Grammont, aujourd’hui conservé à l’abbaye de Maredsous, a vu le jour vers 1450, alors que le comté de Flandre était aux mains de Philippe le Bon, duc de Bourgogne. Le Bréviaire est une œuvre-clé pour la connaissance de la miniature flamande du milieu du XVe siècle.';
    $bannerTitle = 'Un manuscrit d’époque bourguignonne';
    $bannerSubtitle = 'conservé à l’abbaye de Maredsous';
    $footerViewerTekst = 'Voir le volume avec notre visualiseur en ligne';
    $readMore = 'Lire la suite';
    break;
  case "en":
    $taal = "English";
    $titleSite = 'THE BREVIARY OF<br> GERAARDSBERGEN';
    $navs = ['Credits', 'Partners', 'Home', 'Stories', 'Digital edition', 'Breviary of Geraardsbergen', 'A 15th-century masterpiece', 'Research & Conservation'];
    $tekstBanner = 'The Breviary of St Adrian of Geraardsbergen, nowadays kept at Maredsous Abbey, dates from 1450, when the County of Flanders was ruled by Philip the Good, Duke of Burgundy. The Breviary is a key work for the knowledge of Flemish miniature painting of the mid-fifteenth century.';
    $bannerTitle = 'A Burgundian manuscript';
    $bannerSubtitle = 'kept at Maredsous Abbey';
    $footerViewerTekst = 'View the volume in our online viewer';
    $readMore = 'Read more';
    break;
  default:
    $taal = "";
}
?>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

<!-- Add the slick-theme.css if you want default styling -->
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
<!-- Add the slick-theme.css if you want default styling -->
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
<style>
  .nav-link {
    text-decoration: underline;
    color: white;
    display: initial;
  }
  .nav-link:hover{
    color:black;
  }
  .footer-section-2 .nav-link{
    color: black;
  }
  .card-img-top {
    width: 100%;
    height: 15vw;
    object-fit: cover;
    padding-top: 0%;
  }
  section{
    font-family: 'Bitter', serif;
  }
  .container .title{
    font-family: 'Montserrat', sans-serif;
    color: ad3e3f;
  }
  .shadow {
    background: rgba(0, 0, 0, 0.4);
  }
  .hero .slick-slider{
    border:none;
  }
  .slick-dots li button::before{
    font-size: 20px;
    color: white;
  }
  .slick-dots li.slick-active button::before{
    color: white;
  }
  .footer div.col-2{
    height: 75px;
  }
  .footer div.col-2 div{
    height: 120px;
  }
  .footer div.col-2 img{
    max-height: 100%;
  }
  .clickable{
    cursor: pointer;
  }
  .small-nav {
    display: none;
  }
  @media (max-width:600px){
    .nav-link {
      width: 100% !important;
      display: block !important;
      text-decoration: none !important;
      text-align: center !important;
    }
    .hide-small{
      display: none !important;
    }
    .small-nav{
      display: block !important;
    }
  }
</style>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
        <script src="https://kit.fontawesome.com/582fb8c29f.js" crossorigin="anonymous"></script>
        <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&family=Noto+Sans:wght@400;700&display=swap" rel="stylesheet">
        <script src="https://unpkg.com/colcade@0/colcade.js"></script>
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.4.0/dist/leaflet.css"
     integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
     crossorigin="">
     <link href="https://fonts.googleapis.com/css2?family=Bitter&family=Montserrat:wght@600&display=swap" rel="stylesheet"> 


    </head>

    <?php echo $this->htmlElement('body'); ?>
    <?php echo $userBar; ?>


    <section class="section" style="background-color: #ad3e3f;" style="padding:5%;">
    <div class="btn-toolbar justify-content-end" role="toolbar" aria-label="Toolbar with button groups" style="padding-right:5%;">
    <ul class="nav">
      <li class="nav-item">
        <a class="nav-link" href="/s/maredsous-<?php echo $lan;?>/page/credits"><?php echo $navs[0];?></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/s/maredsous-<?php echo $lan;?>/page/partners"><?php echo $navs[1];?></a>
      </li>
    </ul>
    <div class="btn-group small-nav" role="group" aria-label="Third group">
  <button id="btnGroupDrop1" type="button" class="button is-rounded dropdown-toggle" style="background-color: transparent;" data-bs-toggle="dropdown" aria-expanded="false">
    <p style="color:white;"><?php echo $taal;?></p></button>
    <ul class="dropdown-menu" aria-labelledby="btnGroupDrop1">
      <li><a class="dropdown-item" href="/s/maredsous-nl/">Nederlands</a></li>
      <li><a class="dropdown-item" href="/s/maredsous-fr/">Français</a></li>
      <li><a class="dropdown-item" href="/s/maredsous-en/">English</a></li>
    </ul>
  </div>
    </div>
    <div class="btn-toolbar justify-content-between" role="toolbar" aria-label="Toolbar with button groups" style="padding-left: 5%; padding-right:5%; padding-top:1%;">
  <div class="btn-group me-2" role="group" aria-label="First group">
<h1 class="title is-3" style="color:white;font-family: 'Montserrat', sans-serif;"><?php echo $titleSite;?></h1>
  </div>
  <div class="btn-group me-2" role="group" aria-label="Second group">
  <div class="nav justify-content-center">
    <ul class="nav flex-column">
  <li class="nav-item">
    <a class="nav-link" href="/s/maredsous-<?php echo $lan;?>/page/home"><?php echo $navs[2];?></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/s/maredsous-<?php echo $lan;?>/page/stories"><?php echo $navs[3];?></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/s/maredsous-<?php echo $lan;?>/page/digitale_editie"><?php echo $navs[4];?></a>
  </li>
</ul>
<ul class="nav flex-column">
  <li class="nav-item">
    <a class="nav-link"href="/s/maredsous-<?php echo $lan;?>/page/brevier"><?php echo $navs[5];?></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/s/maredsous-<?php echo $lan;?>/page/meesterwerk"><?php echo $navs[6];?></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/s/maredsous-<?php echo $lan;?>/page/onderzoek"><?php echo $navs[7];?></a>
  </li>
</ul>
                </div>
  </div>
  <div class="btn-group hide-small" role="group" aria-label="Third group">
  <button id="btnGroupDrop1" type="button" class="button is-rounded dropdown-toggle" style="background-color: transparent;" data-bs-toggle="dropdown" aria-expanded="false">
    <p style="color:white;"><?php echo $taal;?></p></button>
    <ul class="dropdown-menu" aria-labelledby="btnGroupDrop1">
      <li><a class="dropdown-item" href="/s/maredsous-nl/">Nederlands</a></li>
      <li><a class="dropdown-item" href="/s/maredsous-fr/">Français</a></li>
      <li><a class="dropdown-item" href="/s/maredsous-en/">English</a></li>
    </ul>
  </div>
</div>
    </section>

    <?php if($home): ?>
    <section class="hero is-primary" style="background-color:ad3e3f;">
        <div class="hero-overlay single-item">
          <?php for ($i = 1; $i <= 4; $i++) {
          $hero = 'img/hero' . $i . '.jpg';  
          ?>
          <div class="hero-body" style="background:url('<?php echo $this->assetUrl($hero); ?>') no-repeat center center;background-size: cover;">
            <div class="container">
              <div class="columns">
                <div class="column is-1 logo-column">
                  <?php if ($this->themeSetting('logo')): ?>
                      <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
                  <?php endif; ?>
                </div>
                <div class="column is-6 shadow">
                  <h1 class="title is-1"><?php echo $bannerTitle; ?></h1>
                  <h2 class="subtitle is-4"><?php echo $bannerSubtitle; ?></h2>
                  <?php if($home):?>
                    <div class="hero-text">
                      <div class="content">
                        <p>
                        <?php echo $tekstBanner;?>
                        </p>
                      </div>
                    </div>
                    <button class="btn btn-primary is-square" style="background-color: ad3e3f;border-radius:0%; border-color:ad3e3f;margin-top:2%;"><a href="/s/maredsous-<?php echo $lan;?>/page/brevier"><?php echo $readMore;?></a></button>
                  <?php endif;?>
                </div>
              </div>
            </div>
           </div>
          <?php } ?>
         </div>
      </section>
  <?php endif; ?>

    <?php echo $this->content; ?>

    <footer class="footer" style="background-color:ad3e3f;">
    <?php if($vol):
    $case = substr($url,-1);
    switch ($case){
      case "1":
        $mira = "https://resolver.libis.be/IE16535501/representation";
        break;
      case "2":
        $mira = "https://resolver.libis.be/IE16539691/representation";
        break;
      case "3":
        $mira = "https://resolver.libis.be/IE16537325/representation";
        break;
      case "4":
        $mira = "https://resolver.libis.be/IE16541421/representation";
        break;
      default:
        $mira = "";
    }
    ?>

<section class="text-center" style="height: 100px;">
<div style="padding-top:1%;"><img src="<?php echo $this->assetUrl("img/eye2.png");?>"></div>
<div><a href="<?php echo $mira;?>" target="_blank"><?php echo $footerViewerTekst;?></a></div>
</section>
<?php endif;?>
      <div class="section footer-section" style="background-color: eae6e0;height:150px;">
        <div class="container">
          <nav class="level">
          <div class="row">
          <div class="col-2 align-items-center justify-content-center d-flex">
<div>
<img class="clickable" id="abdij" alt="Abdij van Maredsous" src="<?php echo $this->assetUrl("img/01_Maredsous.png");?>" />
  </div>
</div>

  <div class="col-2 align-items-center justify-content-center d-flex">

      <img class="clickable" id="KUL" alt="KU Leuven" src="<?php echo $this->assetUrl("img/02_index.png");?>" />

  </div>
  <div class="col-2 align-items-center justify-content-center d-flex">

      <img class="clickable" id="IRPAKIK" alt="IRPAKIK" src="<?php echo $this->assetUrl("img/03_images.png");?>" />

  </div>
  <div class="col-2 align-items-center justify-content-center d-flex">

<img class="clickable" id="illuminare" alt="Illuminare" src="<?php echo $this->assetUrl("img/04_illuminare.png");?>" />

</div>
  <div class="col-2 align-items-center justify-content-center d-flex">

      <img class="clickable" id="koning" alt="Koning Boudewijnstichting" src="<?php echo $this->assetUrl("img/05.png");?>" />

  </div>
  <div class="col-2 align-items-center justify-content-center d-flex">

      <img class="clickable" id="fonds" alt="Fonds Baillet Latour" src="<?php echo $this->assetUrl("img/06.png");?>" />

  </div>
</div>
            </nav>

        </div>
      </div>
      <div class="section footer-section-2" style="padding: 1.5rem 0;background-color:f3f0ec; color:black;">
      <div class="btn-toolbar justify-content-between" role="toolbar" aria-label="Toolbar with button groups" style="padding-left: 5%; padding-right:5%;">
      <div class="btn-group me-2" role="group" aria-label="First group">
      <h1 class="title is-5" style="font-family: 'Montserrat', sans-serif; color:black;"><?php echo $titleSite;?></h1>
  </div>
  <div class="btn-group me-2" role="group" aria-label="Second group">
  <div class="nav justify-content-center">
    <ul class="nav flex-column">
  <li class="nav-item">
    <a class="nav-link" href="/s/maredsous-<?php echo $lan;?>/page/home"><?php echo $navs[2];?></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/s/maredsous-<?php echo $lan;?>/page/stories"><?php echo $navs[3];?></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/s/maredsous-<?php echo $lan;?>/page/digitale_editie"><?php echo $navs[4];?></a>
  </li>
</ul>
<ul class="nav flex-column">
  <li class="nav-item">
    <a class="nav-link"href="/s/maredsous-<?php echo $lan;?>/page/brevier"><?php echo $navs[5];?></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/s/maredsous-<?php echo $lan;?>/page/meesterwerk"><?php echo $navs[6];?></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/s/maredsous-<?php echo $lan;?>/page/onderzoek"><?php echo $navs[7];?></a>
  </li>
</ul>
<ul class="nav small-nav flex-column">
  <li class="nav-item">
    <a class="nav-link" href="/s/maredsous-<?php echo $lan;?>/page/credits"><?php echo $navs[0];?></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/s/maredsous-<?php echo $lan;?>/page/partners"><?php echo $navs[1];?></a>
  </li>
  </ul>
  <ul class="nav small-nav flex-column">
  <li class="nav-item">
    <a class="nav-link" href="https://libis.be/">© KU Leuven, built by LIBIS</a>
  </li>
</ul>
                </div>
  </div>
  <div class="btn-group hide-small" role="group" aria-label="Third group">
  <ul class="nav flex-column">
  <li class="nav-item">
    <a class="nav-link" href="/s/maredsous-<?php echo $lan;?>/page/credits"><?php echo $navs[0];?></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/s/maredsous-<?php echo $lan;?>/page/partners"><?php echo $navs[1];?></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" style="text-decoration: none;" href="https://libis.be/">© KU Leuven, built by LIBIS</a>
  </li>
</ul>
</div>
      </div>
                </div>
    </footer>

      <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </body>
  <script>
  $(document).ready(function() {
    $("#abdij").click(function() {
  window.open('https://www.maredsous.com','_blank');
    });
    $("#KUL").click(function() {
  window.open('https://www.kuleuven.be/kuleuven/','_blank');
    });
    $("#IRPAKIK").click(function() {
  window.open('https://www.kikirpa.be/','_blank');
    });
    $("#illuminare").click(function() {
  window.open('http://www.illuminare.be/','_blank');
    });
    $("#koning").click(function() {
  window.open('https://kbs-frb.be/','_blank');
    });
    $("#fonds").click(function() {
  window.open('https://www.fondsbailletlatour.com/','_blank');
    });
    $(".divtest").slick();
    $('.single-item').slick({
      dots: true,
      autoplay: true,
      autoplaySpeed: 5000,
      fade: true,
      cssEase: 'linear',
      arrows: false
    });
  });
  </script>
</html>
